apiVersion: v1
kind: Service
metadata:
  name: softwareone-svc
  namespace: checklistdemo
  labels: 
    name: softwareone-svc
spec: 
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    name: softwareone-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: softwareone-deploy
  namespace: checklistdemo
  labels: 
    name: softwareone-app
spec: 
  replicas: 1
  template: 
    metadata:
      labels: 
        name: softwareone-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - image: subjerepo.azurecr.io/k8sdemo:${{ github.run_id }} 
        name: checklist-container
        resources: 
          requests:
            cpu: "20m"
            memory: "55Mi"
        env:
        - name: testEnv
          value: testEnv
        ports:
        - containerPort: 3000
          name: softwareone-app
        imagePullPolicy: Always
      restartPolicy: Always